name = "quotes-lifeinsurance"
main = ".open-next/worker.js"
compatibility_date = "2025-09-01"
compatibility_flags = ["nodejs_compat"]

[assets]
directory = ".open-next/assets"

[vars]
NEXT_PUBLIC_GOOGLE_PLACES_API_KEY = ""
